// <auto-generated />
using System;
using Lift.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lift.Data.Migrations
{
    [DbContext(typeof(LiftDbContext))]
    partial class LiftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lift.Data.Models.LiftEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LiftEvents");
                });

            modelBuilder.Entity("Lift.Data.Models.ProcessInterruption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("RestartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RestartedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StoppedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoppedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestartedByUserId");

                    b.HasIndex("StoppedByUserId");

                    b.ToTable("ProcessInterruptions");
                });

            modelBuilder.Entity("Lift.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$3P57MKhJUmv8Q0z2PVOoy.TlUfHogbzRrZyYutsQjzWeyATE498By",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Lift.Data.Models.ProcessInterruption", b =>
                {
                    b.HasOne("Lift.Data.Models.User", "RestartedByUser")
                        .WithMany()
                        .HasForeignKey("RestartedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lift.Data.Models.User", "StoppedByUser")
                        .WithMany()
                        .HasForeignKey("StoppedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RestartedByUser");

                    b.Navigation("StoppedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
